apiVersion: v2
description: Helm chart for the IBM FHIR Server
name: ibm-fhir-server
version: 0.3.2
appVersion: 4.9.2
dependencies:
  - name: postgresql
    version: 10.12.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/Alvearie/alvearie-helm
  - https://github.com/IBM/FHIR
home: https://ibm.github.io/FHIR/
type: application
maintainers:
  - name: Lee Surprenant
    email: lmsurpre@us.ibm.com
  - name: Mike Schroeder
    email: mschroed@us.ibm.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed, and security.
    - kind: added
      description: updating to ibm-fhir-schematool v4.9.2's image as default
