apiVersion: v2
description: Helm chart for the IBM FHIR Server
name: ibm-fhir-server
version: 0.5.2
appVersion: 4.10.2
dependencies:
  - name: postgresql
    version: 10.13.14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: keycloak
    version: 16.0.4
    repository: https://codecentric.github.io/helm-charts
    condition: keycloak.enabled
sources:
  - https://github.com/Alvearie/alvearie-helm
  - https://github.com/IBM/FHIR
home: https://ibm.github.io/FHIR/
type: application
maintainers:
  - name: Lee Surprenant
    email: lmsurpre@us.ibm.com
  - name: Mike Schroeder
    email: mschroed@us.ibm.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed, and security.
    - kind: added
      description: switch for schema migration job auto-removal
    - kind: changed
      description: upgrade to ibm-fhir-server 4.10.2
    - kind: changed
      description: upgrade bitnami/postgresql subchart version to 10.13.14
    - kind: changed
      description: upgrade codecentric/keycloak subchart version to 16.0.4
