apiVersion: v2
description: Helm chart for the IBM FHIR Server
name: ibm-fhir-server
version: 0.7.0
appVersion: 4.11.1
dependencies:
  - name: postgresql
    version: 10.13.15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: keycloak
    version: 18.1.1
    repository: https://codecentric.github.io/helm-charts
    condition: keycloak.enabled
sources:
  - https://github.com/Alvearie/alvearie-helm
  - https://github.com/IBM/FHIR
home: https://ibm.github.io/FHIR/
type: application
maintainers:
  - name: Lee Surprenant
    email: lmsurpre@us.ibm.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed, and security.
    - kind: changed
      description: bump default ibm-fhir-server image from 4.10.2 to 4.11.1
    - kind: changed
      description: bump keycloak subchart from 17.0.3 to 18.1.1
    - kind: changed
      description: bump default smart-keycloak and keycloak-config images from 0.4.1 to 0.5.1
