apiVersion: v2
description: Helm chart for the IBM FHIR Server
name: ibm-fhir-server
version: 0.5.1
appVersion: 4.10.0
dependencies:
  - name: postgresql
    version: 10.13.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: keycloak
    version: 15.1.0
    repository: https://codecentric.github.io/helm-charts
    condition: keycloak.enabled
sources:
  - https://github.com/Alvearie/alvearie-helm
  - https://github.com/IBM/FHIR
home: https://ibm.github.io/FHIR/
type: application
maintainers:
  - name: Lee Surprenant
    email: lmsurpre@us.ibm.com
  - name: Mike Schroeder
    email: mschroed@us.ibm.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed, and security.
    - kind: changed
      description: move jvm.options to configDropins to avoid overwriting
    - kind: changed
      description: upgrade to ibm-fhir-server 4.10.0
    - kind: changed
      description: reduce the default initial heap size and memory request
    - kind: changed
      description: upgrade postgresql image to 13.5 and subchart to 10.13.8
