ingress:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: >-
      add_header Strict-Transport-Security "max-age=86400; includeSubDomains";
    nginx.ingress.kubernetes.io/proxy-body-size: 4M
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-protocols: TLSv1.2 TLSv1.3
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "true"
