# Default values for chart.

# -- Optional override for the fully qualified name of the created kube resources
fullnameOverride:
# -- Optional override for chart name portion of the created kube resources
nameOverride:

# -- The number of replicas for the externally-facing FHIR server pods
replicaCount: 2
image:
  repository: ibmcom/ibm-fhir-server
  tag: "4.9.1"
  pullPolicy: Always
imagePullSecrets: []
# -- Set to true to restrict the API to a particular set of resource type endpoints
restrictEndpoints: false
# -- Control which interactions are supported for which resource type endpoints
# @default -- A single entry for resourceType "Resource" that applies to all resource types
endpoints:
  - # -- A valid FHIR resource type; use "Resource" for whole-system behavior
    resourceType: Resource
    # -- (list) Valid _include arguments while searching this resource type; nil means no restrictions
    searchIncludes:
    # -- (list) Valid _revInclude arguments while searching this resource type; nil means no restrictions
    searchRevIncludes:
    # -- (list) Instances of this type must claim conformance to at least one of the listed profiles; nil means no profile conformance required
    profiles:
    # -- A mapping from enabled search parameter codes to search parameter definitions
    searchParameters:
      - code: "*"
        url: "*"
    # -- The set of enabled interactions for this resource type:
    # [create, read, vread, history, search, update, patch, delete]
    # @default -- All interactions.
    interactions:
      - create
      - read
      - vread
      - history
      - search
      - update
      - patch
      - delete
db:
  type: postgresql
  host: postgres
  port: 5432
  enableTls: false
  name: postgres
  user: postgres
  # -- The name of a Secret from which to retrieve database information.
  # If this value is set, it is expected that passwordSecretKey and/or apiKeySecretKey will also be set.
  dbSecret: postgres
  # -- For the Secret specified in dbSecret, the key of the key/value pair containing the password.
  # This value will be ignored if the dbSecret value is not set.
  passwordSecretKey: postgresql-password
  # -- For the Secret specified in dbSecret, the key of the key/value pair containing the apiKey.
  # This value will be ignored if the dbSecret value is not set.
  apiKeySecretKey:
  # -- The database password. If dbSecret is set, the password will be set from its contents.
  password:
  # -- The database apiKey. If apiKeySecret is set, the apiKey will be set from its contents.
  apiKey:
  schema: fhirdata
  tenantKey:
  sslConnection: true
  pluginName:
  securityMechanism:
schemaMigration:
  enabled: true
  image:
    repository: ibmcom/ibm-fhir-schematool
    tag: "4.9.1"
    pullPolicy: Always
    pullSecret: all-icr-io
# -- The name of a Secret from which to retrieve fhirUserPassword and fhirAdminPassword.
# If this value is set, it is expected that fhirUserPasswordSecretKey and fhirAdminPasswordSecretKey will also be set.
fhirPasswordSecret:
# -- For the Secret specified in fhirPasswordSecret, the key of the key/value pair containing the fhirUserPassword.
# This value will be ignored if the fhirPasswordSecret value is not set.
fhirUserPasswordSecretKey:
# -- For the Secret specified in fhirPasswordSecret, the key of the key/value pair containing the fhirAdminPassword.
# This value will be ignored if the fhirPasswordSecret value is not set.
fhirAdminPasswordSecretKey:
# -- The fhirUserPassword. If fhirPasswordSecret is set, the fhirUserPassword will be set from its contents.
fhirUserPassword: change-password
# -- The fhirAdminPassword. If fhirPasswordSecret is set, the fhirAdminPassword will be set from its contents.
fhirAdminPassword: change-password
# -- Indicates whether the server registry resource provider should be used by the FHIR registry component to access definitional resources through the persistence layer
serverRegistryResourceProviderEnabled: false
audit:
  enabled: false
  kafkaServers:
  kafkaApiKey:
  kafka:
    bootstrapServers:
    securityProtocol: SASL_SSL
    saslMechanism: PLAIN
    saslJaasConfig:
    sslEnabledProtocols: TLSv1.2
    sslProtocol: TLSv1.2
    sslEndpointIdentificationAlgorithm: HTTPS
  # -- The target Kafka topic for audit events
  topic: FHIR_AUDIT_DEV
  # -- `cadf` or `auditevent`
  type: auditevent
  # -- The city where the server is running
  geoCity:
  # -- The state where the server is running
  geoState:
  # -- The country where the server is running
  geoCountry:
notifications:
  kafka:
    enabled: false
    topicName:
    bootstrapServers:
    securityProtocol: SASL_SSL
    saslMechanism: PLAIN
    saslJaasConfig:
    sslEnabledProtocols: TLSv1.2
    sslProtocol: TLSv1.2
    sslEndpointIdentificationAlgorithm: HTTPS
  nats:
    enabled: false
    cluster:
    channel:
    clientId:
    servers:
    useTLS: true
    truststoreLocation:
    truststorePassword:
    keystoreLocation:
    keystorePassword:
objectStorage:
  enabled: false
  # -- The name of a Secret from which to retrieve object storage information.
  # If this value is set, it is expected that locationSecretKey, endpointSecretKey, accessKeySecretKey, and secretKeySecretKey will also be set.
  objectStorageSecret:
  # -- For the Secret specified in objectStorageSecret, the key of the key/value pair containing the location.
  # This value will be ignored if the objectStorageSecret value is not set.
  locationSecretKey:
  # -- For the Secret specified in objectStorageSecret, the key of the key/value pair containing the endpoint URL.
  # This value will be ignored if the objectStorageSecret value is not set.
  endpointUrlSecretKey:
  # -- For the Secret specified in objectStorageSecret, the key of the key/value pair containing the access key.
  # This value will be ignored if the objectStorageSecret value is not set.
  accessKeySecretKey:
  # -- For the Secret specified in objectStorageSecret, the key of the key/value pair containing the secret key.
  # This value will be ignored if the objectStorageSecret value is not set.
  secretKeySecretKey:
  # -- The object storage location. If objectStorageSecret is set, the location will be set from its contents.
  location:
  # -- The object storage endpoint URL. If objectStorageSecret is set, the endpoint URL will be set from its contents.
  endpointUrl:
  # -- The object storage access key. If objectStorageSecret is set, the access key will be set from its contents.
  accessKey:
  # -- The object storage secret key. If objectStorageSecret is set, the secret key will be set from its contents.
  secretKey:
  # -- Bucket names must be globally unique
  bulkDataBucketName:
  batchIdEncryptionKey:
ingress:
  enabled: true
  annotations: {}
  # -- The default cluster hostname, used for both ingress.rules.host and ingress.tls.hosts.
  # If you have more than one, you'll need to set overrides for the rules and tls separately.
  hostname: fhir.example.com
  rules:
    - host: "{{ .Release.Name }}.{{ $.Values.ingress.hostname }}"
      paths:
        - "/"
  servicePort: https
  tls:
    - secretName: ""
      hosts:
        - "{{ $.Values.ingress.hostname }}"
resources:
  requests:
    memory: "4Gi"
    ephemeral-storage: "1Gi"
  limits:
    memory: "5Gi"
    ephemeral-storage: "1Gi"

# -- Template containing the fhir-server-config.json content
fhirServerConfigTemplate: "defaultFhirServerConfig"

# -- Template containing the datasources.xml content
datasourcesTemplate: "defaultPostgresDatasources"

# -- Template containing the extension-search-parameters.json content
extensionSearchParametersTemplate: "defaultSearchParameters"
