repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.5.0
    hooks:
      - id: helm-docs
        args:
          # Repeating the flag adds this to the list
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl
