apiVersion: v1
kind: Service
metadata:
  name: {{ template "fhir.fullname" . }}
  labels:
    {{- include "fhir.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "fhir.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: https
      protocol: TCP
      port: 9443
  {{- if .Values.exposeHttpEndpoint }}
    - name: http
      protocol: TCP
      port: {{ .Values.exposeHttpPort }}
      targetPort: 9080
  {{- end }}
