apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fhir.fullname" . }}-config
  labels:
    {{- include "fhir.labels" . | nindent 4 }}
data:
  datasources.xml: >
    {{- include .Values.datasourcesTemplate . }}
  extension-search-parameters.json: >
    {{- include .Values.extensionSearchParametersTemplate . }}
  fhir-server-config.json: >
    {{- include .Values.fhirServerConfigTemplate . }}
