apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fhir.fullname" . }}-config
  labels:
    {{- include "fhir.labels" . | nindent 4 }}
data:
  datasources.xml: >
    {{- include .Values.datasourcesTemplate . }}
  extension-search-parameters.json: >
    {{- include .Values.extensionSearchParametersTemplate . }}
  fhir-server-config.json: >
    {{- include .Values.fhirServerConfigTemplate . }}
  jvm.options: |
    {{- if .Values.minHeap }}
    # Initial heap size
    -Xms{{ .Values.minHeap }}
    {{- end }}
    {{- if .Values.maxHeap }}
    # Maximum heap size
    -Xmx{{ .Values.maxHeap }}
    {{- end }}

    {{- with .Values.extraJvmOptions }}
    {{ tpl . $ | nindent 4 }}
    {{- end }}
  {{- if .Values.exposeHttpEndpoint }}
  expose-http-endpoint.xml: >
    <server>
      <!-- Serve non-TLS traffic on port 9080 -->
      <httpEndpoint id="defaultHttpEndpoint" httpPort="9080"/>
    </server>
  {{- end }}
