apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fhir.fullname" . }}-user-secret
  labels:
    {{- include "fhir.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.fhirUserPassword }}
  fhir.user.password: {{ .Values.fhirUserPassword | b64enc }}
  {{- end }}
  {{- if .Values.fhirAdminPassword }}
  fhir.admin.password: {{ .Values.fhirAdminPassword | b64enc }}
  {{- end }}
