apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fhir.fullname" . }}-user-secret
  labels:
    app: {{ template "fhir.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.fhirUserPassword }}
  fhir.user.password: {{ .Values.fhirUserPassword | b64enc }}
  {{- end }}
  {{- if .Values.fhirAdminPassword }}
  fhir.admin.password: {{ .Values.fhirAdminPassword | b64enc }}
  {{- end }}
