apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fhir.fullname" . }}-db-secret
  labels:
    {{- include "fhir.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.db.password }}
  password: {{ .Values.db.password | b64enc }}
  {{- end }}
  {{- if .Values.db.apiKey }}
  apiKey: {{ .Values.db.apiKey | b64enc }}
  {{- end }}
