{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak.fullname" .Subcharts.keycloak }}-admin-secret
  labels:
    {{- include "fhir.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.keycloak.adminUsername | b64enc }}
  password: {{ .Values.keycloak.adminPassword | b64enc }}
{{- end }}
