{{- if .Values.objectStorage.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fhir.fullname" . }}-object-storage-secret
  labels:
    app: {{ template "fhir.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.objectStorage.location }}
  cos.location: {{ .Values.objectStorage.location | b64enc }}
  {{- end }}
  {{- if .Values.objectStorage.endpointUrl }}
  cos.endpoint.url.internal: {{ .Values.objectStorage.endpointUrl | b64enc }}
  cos.endpoint.url.external: {{ .Values.objectStorage.endpointUrl | b64enc }}
  {{- end }}
  {{- if .Values.objectStorage.accessKey }}
  cos.access.key: {{ .Values.objectStorage.accessKey | b64enc }}
  {{- end }}
  {{- if .Values.objectStorage.secretKey }}
  cos.secret.key: {{ .Values.objectStorage.secretKey | b64enc }}
  {{- end }}
{{- end -}}
