{{- if .Values.schemaMigration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fhir.fullname" . }}-update-schema
  labels:
    app: {{ template "fhir.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    # Hook weights can be positive or negative numbers but must be represented as strings.
    # When Helm starts the execution cycle of hooks of a particular Kind it will sort those hooks in ascending order.
    # So make sure this number is higher than the create-schemas weight.
    "helm.sh/hook-weight": "2"
    # before-hook-creation	Delete the previous resource before a new hook is launched (default)
    # hook-succeeded	Delete the resource after the hook is successfully executed
    # hook-failed	Delete the resource if the hook failed during execution
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-schematool"
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ .Values.schemaMigration.image.pullSecret }}
      containers:
        - name: fhir-schematool
          image: {{ .Values.schemaMigration.image.repository }}:{{ .Values.schemaMigration.image.tag }}
          env:
            - name: FHIR_DB_HOSTNAME
              value: "{{ include "fhir.database.host" $ }}"
            - name: FHIR_DB_PORT
              value: "{{ include "fhir.database.port" $ }}"
            - name: FHIR_DB_NAME
              value: "{{ include "fhir.database.name" $ }}"
            - name: FHIR_DB_USER
              value: "{{ include "fhir.database.user" $ }}"
            - name: FHIR_DB_SCHEMA
              value: {{ .Values.db.schema }}
            - name: FHIR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "fhir.database.secretName" $ }}"
                  key: "{{ include "fhir.database.secretKey" $ }}"
          command:
            - bash
            - -c
            - /opt/java/openjdk/bin/java -jar /opt/schematool/fhir-persistence-schema-*-cli.jar
              --db-type {{ .Values.db.type }}
              --prop db.host=${FHIR_DB_HOSTNAME}
              --prop db.port=${FHIR_DB_PORT}
              --prop db.database=${FHIR_DB_NAME}
              --prop user=${FHIR_DB_USER}
              --prop password=${FHIR_DB_PASSWORD}
              {{- if .Values.db.enableTls }}
              {{- if eq .Values.db.type "db2" }}
              --prop sslConnection=true
              {{- else }}
              --prop ssl=true
              --prop sslmode=verify-full
              --prop sslrootcert=/opt/schematool/workarea/db.cert
              {{- end }}
              {{- end }}
              --schema-name {{ .Values.db.schema }}
              --update-schema
  backoffLimit: 4
{{- end -}}
