apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: fhir-server-config
          configMap:
            name: fhir-server-config
      containers:
        - name: {{ template "name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: fhir-server-config
              mountPath: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/datasources.xml
              subPath: datasources.xml
            - name: fhir-server-config
              mountPath: /opt/ol/wlp/usr/servers/defaultServer/config/default
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SEC_TLS_TRUSTDEFAULTCERTS
              value: "true"
            - name: TRACE_SPEC
              value: "*=info:com.ibm.fhir.*=info"
            - name: WLP_LOGGING_MESSAGE_FORMAT
              value: json
            - name: WLP_LOGGING_MESSAGE_SOURCE
              value: ""
            - name: WLP_LOGGING_CONSOLE_FORMAT
              value: json
            - name: WLP_LOGGING_CONSOLE_LOGLEVEL
              value: info
            - name: WLP_LOGGING_CONSOLE_SOURCE
              value: message,trace,accessLog,ffdc,audit
            - name: WLP_LOGGING_JSON_FIELD_MAPPINGS
              value: loglevel:level
            - name: FHIR_DB_HOSTNAME
              value: "{{ .Values.db.host }}"
            - name: FHIR_DB_PORT
              value: "{{ .Values.db.port }}"
            - name: FHIR_DB_NAME
              value: "{{ .Values.db.name }}"
            - name: FHIR_DB_USERNAME
              value: "{{ .Values.db.username }}"
            - name: FHIR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.passwordSecret }}
                  key: postgresql-password
            - name: FHIR_DB_SCHEMA
              value: {{ .Values.db.schema }}
            - name: DS_MIN_POOL_SIZE
              value: "20"
            - name: DS_MAX_POOL_SIZE
              value: "100"
            - name: DS_AGED_TIMEOUT
              value: "-1"
            - name: BATCH_DB_HOSTNAME
              value: "{{ .Values.db.host }}"
            - name: BATCH_DB_PORT
              value: "{{ .Values.db.port }}"
            - name: BATCH_DB_NAME
              value: "{{ .Values.db.name }}"
            - name: BATCH_DB_USER
              value: "{{ .Values.db.username }}"
            - name: BATCH_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.passwordSecret }}
                  key: postgresql-password
            - name: COS_LOCATION
              valueFrom:
                secretKeyRef:
                  name: object-storage-secret
                  key: cos.location
            - name: COS_ENDPOINT_INTERNAL
              valueFrom:
                secretKeyRef:
                  name: object-storage-secret
                  key: cos.endpoint.url.internal
            - name: COS_ENDPOINT_EXTERNAL
              valueFrom:
                secretKeyRef:
                  name: object-storage-secret
                  key: cos.endpoint.url.external
            - name: COS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: object-storage-secret
                  key: cos.access.key
            - name: COS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: object-storage-secret
                  key: cos.secret.key
            - name: COS_BUCKET
              value: {{ .Values.objectStorage.bulkDataBucketName }}
            - name: FHIR_USER_PASSWORD
              value: {{ .Values.fhirUserPassword }}
            - name: FHIR_ADMIN_PASSWORD
              value: {{ .Values.fhirAdminPassword }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /fhir-server/api/v4/$healthcheck
              port: {{ .Values.service.internalPort }}
              httpHeaders:
                - name: Authorization
                  value: Basic {{ print "fhiruser:" .Values.fhirUserPassword | b64enc }}
            initialDelaySeconds: 36
            periodSeconds: 10
            timeoutSeconds: 4
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - "/opt/ol/wlp/bin/server status"
            initialDelaySeconds: 32
            periodSeconds: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 32
