apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fhir.fullname" . }}
  labels:
    app: {{ template "fhir.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fhir.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "fhir.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: fhir-server-config
          configMap:
            name: {{ template "fhir.fullname" . }}-config
      containers:
        - name: {{ template "fhir.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 9443
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: fhir-server-config
              mountPath: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/datasources.xml
              subPath: datasources.xml
            - name: fhir-server-config
              mountPath: /opt/ol/wlp/usr/servers/defaultServer/config/default
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SEC_TLS_TRUSTDEFAULTCERTS
              value: "true"
            - name: TRACE_SPEC
              value: "*=info:com.ibm.fhir.*=info"
            - name: WLP_LOGGING_MESSAGE_FORMAT
              value: json
            - name: WLP_LOGGING_MESSAGE_SOURCE
              value: ""
            - name: WLP_LOGGING_CONSOLE_FORMAT
              value: json
            - name: WLP_LOGGING_CONSOLE_LOGLEVEL
              value: info
            - name: WLP_LOGGING_CONSOLE_SOURCE
              value: message,trace,accessLog,ffdc,audit
            - name: WLP_LOGGING_JSON_FIELD_MAPPINGS
              value: loglevel:level
            - name: FHIR_DB_HOSTNAME
              value: "{{ .Values.db.host }}"
            - name: FHIR_DB_PORT
              value: "{{ .Values.db.port }}"
            - name: FHIR_DB_NAME
              value: "{{ .Values.db.name }}"
            - name: FHIR_DB_USER
              value: "{{ .Values.db.user }}"
            {{- if .Values.db.dbSecret }}
            {{- if .Values.db.passwordSecretKey }}
            - name: FHIR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.dbSecret }}
                  key: {{ .Values.db.passwordSecretKey }}
            {{- end }}
            {{- if .Values.db.apiKeySecretKey }}
            - name: FHIR_DB_APIKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.dbSecret }}
                  key: {{ .Values.db.apiKeySecretKey }}
            {{- end }}
            {{- else }}
            {{- if .Values.db.password }}
            - name: FHIR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fhir-db-secret
                  key: password
            {{- end }}
            {{- if .Values.db.apiKey }}
            - name: FHIR_DB_APIKEY
              valueFrom:
                secretKeyRef:
                  name: fhir-db-secret
                  key: apiKey
            {{- end }}
            {{- end }}
            - name: FHIR_DB_SCHEMA
              value: {{ .Values.db.schema }}
            - name: FHIR_DB_SSL
              value: "{{ .Values.db.sslConnection }}"
            {{- if .Values.db.pluginName }}
            - name: FHIR_DB_PLUGIN
              value: {{ .Values.db.pluginName }}
            {{- end }}
            {{- if .Values.db.securityMechanism }}
            - name: FHIR_DB_SECURITY
              value: {{ .Values.db.securityMechanism }}
            {{- end }}
            - name: DS_MIN_POOL_SIZE
              value: "20"
            - name: DS_MAX_POOL_SIZE
              value: "100"
            - name: DS_AGED_TIMEOUT
              value: "-1"
            {{- if .Values.objectStorage.enabled }}
            - name: BATCH_DB_HOSTNAME
              value: "{{ .Values.db.host }}"
            - name: BATCH_DB_PORT
              value: "{{ .Values.db.port }}"
            - name: BATCH_DB_NAME
              value: "{{ .Values.db.name }}"
            - name: BATCH_DB_USER
              value: "{{ .Values.db.user }}"
            {{- if .Values.db.dbSecret }}
            {{- if .Values.db.passwordSecretKey }}
            - name: BATCH_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.dbSecret }}
                  key: {{ .Values.db.passwordSecretKey }}
            {{- end }}
            {{- if .Values.db.apiKeySecretKey }}
            - name: BATCH_DB_APIKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.dbSecret }}
                  key: {{ .Values.db.apiKeySecretKey }}
            {{- end }}
            {{- else }}
            {{- if .Values.db.password }}
            - name: BATCH_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fhir-db-secret
                  key: password
            {{- end }}
            {{- if .Values.db.apiKey }}
            - name: BATCH_DB_APIKEY
              valueFrom:
                secretKeyRef:
                  name: fhir-db-secret
                  key: apiKey
            {{- end }}
            {{- end }}
            - name: BATCH_DB_SSL
              value: "{{ .Values.db.sslConnection }}"
            {{- if .Values.db.pluginName }}
            - name: BATCH_DB_PLUGIN
              value: {{ .Values.db.pluginName }}
            {{- end }}
            {{- if .Values.db.securityMechanism }}
            - name: BATCH_DB_SECURITY
              value: {{ .Values.db.securityMechanism }}
            {{- end }}
            {{- if .Values.objectStorage.objectStorageSecret }}
            - name: COS_LOCATION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.objectStorage.objectStorageSecret }}
                  key: {{ .Values.objectStorage.locationSecretKey }}
            - name: COS_ENDPOINT_INTERNAL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.objectStorage.objectStorageSecret }}
                  key: {{ .Values.objectStorage.endpointUrlSecretKey }}
            - name: COS_ENDPOINT_EXTERNAL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.objectStorage.objectStorageSecret }}
                  key: {{ .Values.objectStorage.endpointUrlSecretKey }}
            - name: COS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.objectStorage.objectStorageSecret }}
                  key: {{ .Values.objectStorage.accessKeySecretKey }}
            - name: COS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.objectStorage.objectStorageSecret }}
                  key: {{ .Values.objectStorage.secretKeySecretKey }}
            {{- else }}
            - name: COS_LOCATION
              valueFrom:
                secretKeyRef:
                  name: object-storage-secret
                  key: cos.location
            - name: COS_ENDPOINT_INTERNAL
              valueFrom:
                secretKeyRef:
                  name: object-storage-secret
                  key: cos.endpoint.url.internal
            - name: COS_ENDPOINT_EXTERNAL
              valueFrom:
                secretKeyRef:
                  name: object-storage-secret
                  key: cos.endpoint.url.external
            - name: COS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: object-storage-secret
                  key: cos.access.key
            - name: COS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: object-storage-secret
                  key: cos.secret.key
            {{- end }}
            {{- end }}
            {{- if .Values.fhirPasswordSecret }}
            - name: FHIR_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fhirPasswordSecret }}
                  key: {{ .Values.fhirUserPasswordSecretKey }}
            - name: FHIR_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.fhirPasswordSecret }}
                  key: {{ .Values.fhirAdminPasswordSecretKey }}
            {{- else }}
            - name: FHIR_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fhir-user-secret
                  key: fhir.user.password
            - name: FHIR_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fhir-user-secret
                  key: fhir.admin.password
            {{- end }}
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - "/opt/ol/wlp/bin/server status"
            initialDelaySeconds: 32
            periodSeconds: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 32
