{{- if .Values.objectStorage.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: object-storage-secret
type: Opaque
data:
  cos.location: {{ .Values.objectStorage.location | b64enc }}
  cos.endpoint.url.internal: {{ .Values.objectStorage.endpointUrl | b64enc }}
  cos.endpoint.url.external: {{ .Values.objectStorage.endpointUrl | b64enc }}
  cos.access.key: {{ .Values.objectStorage.accessKey | b64enc }}
  cos.secret.key: {{ .Values.objectStorage.secretKey | b64enc }}
{{- end -}}
