name: Lint and Test Charts

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Install helm-docs
        working-directory: /tmp
        env:
          HELM_DOCS_URL: https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_x86_64.tar.gz
        run: |
          curl -LSs $HELM_DOCS_URL | tar xz && \
          mv ./helm-docs /usr/local/bin/helm-docs && \
          chmod +x /usr/local/bin/helm-docs && \
          helm-docs --version

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pre-commit
        run: pip install pre-commit

      - uses: actions/checkout@v2

      - name: run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

  lint:
    runs-on: ubuntu-22.04
    container: quay.io/helmpack/chart-testing:v3.4.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Run chart-testing (lint)
        run: |
          helm version
          ct version
          pip list
          ct lint --config .ct/config.yaml

  test:
    runs-on: ubuntu-22.04
    needs:
      - lint
      - pre-commit-check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .ct/config.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config .ct/config.yaml
        if: steps.list-changed.outputs.changed == 'true'
